# Generated by Django 4.0.2 on 2022-02-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_fk_user_events_fkuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='fkUser',
            new_name='userFK',
        ),
    ]
