# Generated by Django 4.0.2 on 2022-03-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companies_id'),
        ('events', '0008_rename_fkuser_events_userfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='companyFK',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companies'),
        ),
    ]
