# Generated by Django 4.0.2 on 2022-03-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companies_id'),
        ('events', '0009_events_companyfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='companyFK',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companies'),
        ),
    ]
